### ISSUE TITLE
Mismatch between the size of inference output and the dataset

### ISSUE THREAD

**Issue by Dr-Corgi** [ellenmellon/DIALKI#4]
Hello @ellenmellon ,
I ran this code on the server and found some results confusing to me.

I did some statistics on the validation set of doc2dial, which contains a total of 4256 turns from the agent. However, when I ran `bash ran_eval.sh` for inference, the output only contains 3972 instances.

I further analyze which instances are missing and find that the vast majority of instances on turn-2 (FYI, those instances where the key is `****_2_1`) do not have corresponding predictions. 

The distribution of the validation instances of the doc2dial dataset is as below, (where the list indicates the size of instances at turn_i, respectively):
[660, 174, 407, 208, 421, 258, 389, 272, 381, 276, 373, 190, 153, 55, 33, 4, 2]
However, the distribution of the output comes to:
[660, 1, 407, 192, 421, 223, 383, 251, 372, 259, 369, 187, 153, 55, 33, 4, 2]

I would like to know why most instances on turn-2 disappear, thank you

**Comment by ellenmellon** [comment]
Hi, thanks for reaching out. I think the number is correct. The filtering actually happens in this script: https://github.com/ellenmellon/DIALKI/blob/e7ba6cc9fee70812386ffe79b56fe9ae86984906/prepro/create_dialdoc_json.py#L179

The filtering logic is copied from the original data processing script located here: https://github.com/doc2dial/sharedtask-dialdoc2021/blob/master/scripts/datasets/doc2dial/doc2dial.py

To briefly explain, for consecutive agent turns, we would only consider the last one agent turn as an inference instance. For example, the conversation "user -> agent -> agent -> user" only leads to one inference instance instead of two. But it's interesting to see the distribution to be skewed so much towards turn 2 ..

**Comment by Dr-Corgi** [comment]
@ellenmellon Thank you very much~
